---
resources:
- name: moviefun
  type: git
  source:
    uri: https://github.com/Sundaresancts/apps-movie-fun-code   #<----- REPLACE ME
    branch: spring-boot

- name: deploy-moviefun
  type: cf
  source:
    api: api.system.cumuluslabs.io        #<----- REPLACE ME
    username: sundaresan.kumbeswaran@cognizant.com
    password: {{cf-password}}
    organization: ksundaresan-pal    #<----- REPLACE ME
    space: sandbox         #<----- REPLACE ME
    skip_cert_check: true

jobs:
- name: build
  public: true
  plan:
  - get: moviefun
    trigger: true
  - task: package
    file: moviefun/ci/tasks/package.yml
  - put: deploy-moviefun
    params:
      manifest: moviefun/manifest.yml
      path: package-output/moviefun.war



